# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip:
    - jupyterlite[all]
    - sphinx
    - jupyterlite-sphinx
    - myst-parser
    - sphinx-theme-pd