name: "jupyterlite-pages"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install build environment
        uses: mamba-org/provision-with-micromamba@main

      - name: Build pages
        shell: bash -l {0}
        run: |
          mkdir -p pages
          jupyter lite build --output-dir=pages 

      - name: Commit pages
        run: |
          git config --global user.email "${GH_EMAIL}"
          git config --global user.name "${GH_USERNAME}"
          git add -A
          git diff-index --quiet HEAD || git commit -am `date "+%F-%H-%M-%S"`
          git push
        env: 
          GH_EMAIL: ${{ github.event.commits[0].author.email }}
          GH_USERNAME: ${{ github.event.commits[0].author.username }}

