name: "jupyterlite-pages"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main

      - name: Build pages
        shell: bash -l {0}
        run: |
          mkdir -p pages
          jupyter lite build --output-dir=pages 